INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Vikram Seth', 'Vikram Seth was born on June 20, 1952 in Calcutta, India. He is a writer and actor, known for Highway (2014), A Suitable Boy (2020) and Omnibus (1967).', 'https://m.media-amazon.com/images/M/MV5BMjE5NjkyNTczM15BMl5BanBnXkFtZTgwNDg4MzE5MDE@._V1_QL75_UY133_CR1,0,90,133_.jpg', '1952-06-20', NULL, NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Kiran Desai', 'Pari (2018), Página 2 (2007) and HARDtalk Extra (2004).

*   More at IMDbPro

*   Contact info

*   Agent info

*   Resume

IMDbPro StarmeterSee rank

*   View contact info at IMDbPro', 'https://m.media-amazon.com/images/M/MV5BMTYwNjQ3MjgxN15BMl5BanBnXkFtZTgwNDYwMDY1MjE@._V1_QL75_UY207_CR68,0,140,207_.jpg', NULL, NULL, NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('R.K. Narayan', 'R.K. Narayan was born on October 10, 1906 in Madras, Madras Presidency, British India. R.K. was a writer, known for Guide (1965), Banker Margayya (1983) and The Guide (1965). R.K. died on May 13, 2001 in New Delhi, India.', 'https://m.media-amazon.com/images/M/MV5BYjlhNWRjY2UtYjlmNC00NzFiLWFiZTQtNmU3NTBkNmQ5N2JiXkEyXkFqcGc@._V1_QL75_UX90_CR0,1,90,133_.jpg', '1906-10-10', NULL, NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Amitav Ghosh', 'Ibis, The Calcutta Chromosome and ZIB 09:00 Uhr (2010).

*   More at IMDbPro

*   Contact info

*   Agent info

IMDbPro StarmeterSee rank

Add to favorite people

Add photos, demo reels

*   View contact info at IMDbPro', 'https://m.media-amazon.com/images/M/MV5BYTc1ZjFhZTMtODc1OS00ZWQyLThiOTYtNzk3MDQ4ODAwMmJiXkEyXkFqcGc@._V1_QL75_UX90_CR0,1,90,133_.jpg', NULL, NULL, NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Anita Desai', 'Anita Desai was born on June 24, 1937 in Mussoorie, India. She is a writer, known for In Custody (1994), The Village by the Sea (1991) and In Ismail''s Custody (1994).', 'https://m.media-amazon.com/images/M/MV5BMTUxODc2NTk2MV5BMl5BanBnXkFtZTYwMzg1NjEz._V1_QL75_UY207_CR19,0,140,207_.jpg', '1937-06-24', NULL, NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Khushwant Singh', 'Khushwant Singh was born on February 2, 1915 in Hadali, Khushab district, Punjab, British India. He was an actor and writer, known for Train to Pakistan (1998), Songs and Memories (1992) and Modern India (1960). He was married to Kawal Malik. He died on March 20, 2014 in New Delhi, India.', 'https://m.media-amazon.com/images/M/MV5BMDEzOTY3N2MtNDA2NS00YmEzLTljNTItMDcwOWU1OTc0MTc0XkEyXkFqcGc@._V1_QL75_UY133_CR2,0,90,133_.jpg', '1915-02-02', NULL, NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Ruskin Bond', 'Ruskin Bond was born on May 19, 1934 in Kasauli, Punjab, British India. He is a writer and actor, known for The Blue Umbrella (2005), Junoon (1979) and 7 Khoon Maaf (2011).', 'https://m.media-amazon.com/images/M/MV5BNTAyOTRkY2YtZWM4NS00Yzk1LWFhZjAtYzIxZjY5NDNmZGU2XkEyXkFqcGc@._V1_QL75_UY207_CR72,0,140,207_.jpg', '1934-05-19', NULL, NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('V.S. Naipaul', 'V.S. Naipaul was born on August 17, 1932 in Chaguanas, Trinidad, Trinidad and Tobago. He was a writer, known for The Mystic Masseur (2001), The Levin Interviews (1980) and Bookmark (1983). He was married to Nadira Khannum Alvi and Patricia Ann Hale. He died on August 11, 2018 in London, England, UK.', 'https://m.media-amazon.com/images/M/MV5BZDcwYjUzZmUtNmViZS00MjM1LWIyZTQtODgxNDJiYjlkNDU1XkEyXkFqcGc@._V1_QL75_UY207_CR1,0,140,207_.jpg', '1932-08-17', NULL, NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Rohinton Mistry', 'Rohinton Mistry was born in 1952 in Bombay, India. Rohinton is a writer, known for Such a Long Journey (1998) and A Fine Balance. Rohinton is married to Freny Elavia.', 'https://m.media-amazon.com/images/M/MV5BNzA1MTkxNTgzMl5BMl5BanBnXkFtZTcwMDk0ODUyMQ@@._V1_QL75_UY133_CR2,0,90,133_.jpg', NULL, NULL, NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Smita Nair Jain', NULL, NULL, NULL, NULL, NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Shashi Tharoor', 'Shashi Tharoor was born on March 9, 1956 in London, England, UK. He is a writer, known for Bollywood (1994), U.N. Me (2009) and 8 Billion Angels (2019).', 'https://m.media-amazon.com/images/M/MV5BM2ZmMDVlNDQtOTBkYi00MmZiLWE0NGQtMzg2ZjViMjI3ZDJjXkEyXkFqcGc@._V1_QL75_UX83_.jpg', '1956-03-09', NULL, NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Rabindranath Tagore', 'Rabindranath Tagore was born on May 6, 1861 in Calcutta, Bengal Presidency, British India [now India]. He was a writer and composer, known for Song of the Body, Streer Patra (1972) and Charulata (1964). He was married to Mrinalini Devi. He died on August 7, 1941 in Calcutta, Bengal Presidency, British India [now India].', 'https://m.media-amazon.com/images/M/MV5BODFlYTZhMmYtNmU1NC00NDQyLTg5NzQtNThhZTBlNDVhYWExXkEyXkFqcGc@._V1_QL75_UY207_CR5,0,140,207_.jpg', '1861-05-06', NULL, NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Shobha De', 'Shobha De was born on January 7, 1948 in Bombay, State of Bombay, India. She is a writer and actress, known for Swabhimaan (1995), Lipstick (2002) and Sarrrkkar: Risshton Ki Ankahi Kahani.', 'https://m.media-amazon.com/images/M/MV5BMGU3NGFkZmMtNWE2OC00ZmE5LTg3ZDctZDM0MzhhM2NjMWQwXkEyXkFqcGc@._V1_QL75_UX140_CR0,1,140,207_.jpg', '1948-01-07', NULL, NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Ramachandra Guha', 'It looks like we don''t have any biography for this person yet.Be the first to contribute.', 'https://m.media-amazon.com/images/M/MV5BMTgyMjkyNTE0OF5BMl5BanBnXkFtZTgwMDI1ODM2MjE@._V1_QL75_UY207_CR68,0,140,207_.jpg', NULL, NULL, NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Munshi Premchand', NULL, NULL, NULL, NULL, NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Satyajit Ray', 'w.imdb.com/name/nm0006249/?ref_=nm_ov_bio_lk) was born in Calcutta on May 2, 1921. His father, Late Sukumar Ray was an eminent poet and writer in the history of Bengali literature. In 1940, after receiving his degree in science and economics from Calcutta University, he attended Tagore''s Viswa-Bharati University. His first movie Pather Panchali (1955) won several International Awards and set Ray as a world-class director. He died on April twenty-third, 1992.

Born May 2, 1921

Died April 23, 1992(70)

Born May 2, 1921

Died April 23, 1992(70)

IMDbPro StarmeterSee rank

Add to favorite people

*   Awards

*   83 wins & 23 nominations total', 'https://m.media-amazon.com/images/M/MV5BMTQ4MDA1ODIzMF5BMl5BanBnXkFtZTcwNDU0OTkxOA@@._V1_QL75_UY207_CR65,0,140,207_.jpg', '1921-05-02', NULL, NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Mahasweta Devi', 'Mahasweta Devi was born on January 14, 1926 in Dacca, Bengal Presidency, British India [now in Dhaka, Bangladesh]. She was a writer, known for Sunghursh (1968), Gudia (1997) and Maati Maay (2006). She was married to Asit Gupta and Bijon Bhattacharya. She died on July 28, 2016 in Kolkata, West Bengal, India.', 'https://m.media-amazon.com/images/M/MV5BZWQ3NTJmMGQtOTc4ZS00MGIzLThhNTItMjI3YWU0YTczZjk3XkEyXkFqcGc@._V1_QL75_UY133_CR3,0,90,133_.jpg', '1926-01-14', NULL, NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Jawaharlal Nehru', 'Jawaharlal Nehru was born on November 14, 1889, in Allahabad, India. He was the son of Swaroop Rani and Motilal Nehru, a wealthy lawyer and a prominent leader of the Indian independence movement. The Nehru family belonged to the saraswat Brahmin caste. Nehru graduated from Trinity College, Cambridge University and came back to India in 1912. In 1916, by his parents'' arrangement, he married 17-year-old Kamala from a Kashmiri business family in Delhi. He became the top political leader of the Indian National Congress Party along with his mentor, Mohandas K. Gandhi.

Nehru and his family made transformations in their upper class lifestyle. They followed Gandhi and abandoned fashionable British clothes and expensive possessions. Nehru and his family adopted the native language of Hindu, or Hindustani for their common use. Nehru also wore a khadi kurta and a Gandhi cap as an Indian nationalist uniform. When Nehru''s father joined the Swaraj Party in opposition to Gandhi, Jawaharlal stayed with Gandhi. Together they led the nation of India to independence in 1947.

Nehru signed the first constitution of independent India in 1949. He was an outstanding public speaker. He served as the first Prime Minister of India from 1947 until May 27, 1964, the day he died. He was one of the founders of the international non-aligned movement.

Jawaharlal Nehru was an Indian independence activist, and subsequently, the first Prime Minister of India and a central figure in Indian politics before and after independence. He emerged as an eminent leader of the Indian independence movement and served India as Prime Minister from its establishment as an independent nation in 1947 until his death in 1964. He has been described by the Amar Chitra Katha as the architect of India.', 'https://m.media-amazon.com/images/M/MV5BMjI3MDg1NjM3OF5BMl5BanBnXkFtZTcwMzg4NzkyOA@@._V1_QL75_UY207_CR13,0,140,207_.jpg', '1889-11-14', NULL, NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Mohandas K. Gandhi', 'Mohandas Karamchand Gandhi (Mahatma Gandhi) was born on October 2, 1869, into a Hindu Modh family in Porbanadar, Gujarat, India. His father, named Karamchand Gandhi, was the Chief Minister (diwan) of the city of Porbanadar. His mother, named Putlibai, was the fourth wife; the previous three wives died in childbirth. Gandhi was born into the vaishya (business caste). He was 13 years old when married Kasturbai (Ba) Makhanji, through his parents arrangement. They had four sons. Gandhi learned tolerance and non-injury to living beings from an early age. He was abstinent from meat, alcohol, and promiscuity.

Gandhi studied law at the University of Bombay for one year, then at the University College London, from which he graduated in 1891, and was admitted to the bar of England. His reading of "Civil Disobedience" by David Thoreau inspired his devotion to the principle of non-violence. He returned to Bombay and practiced law there for a year, then went to South Africa to work for an Indian firm in Natal. There Gandhi experienced racism: he was thrown off a train while holding a valid first class ticket and pushed to third class. Later he was beaten by a stagecoach driver for refusing to travel on the foot-board to make room for a European passenger. He was barred from many hotels because of his race. In 1894, Gandhi founded the Natal Indian Congress. They focused on the Indian cause and British discrimination in South Africa. In 1897, Gandhi brought his wife and children to South Africa. He was attacked by a mob of racists, who tried to lynch him. He refused to press charges on any member of the mob. Gandhi became the first non-white lawyer to be admitted to the bar in South Africa.

During the South African War, Gandhi was a stretcher barer. He organized the Indian Ambulance corps of 300 Indian volunteers and hundreds of associates to serve wounded black South Africans. He was decorated for his courage at the Battle of Spion Kop. At that time Gandhi corresponded with Lev Tolstoy and expressed his admiration of the Tolstoyan principles of non-violence. In 1906 Gandhi, for the first time, organized a non-violent resistance against the Transvaal government''s registration act. He called upon his fellow Indians to defy the new law in a non-violent manner and suffer the punishment for doing so. He was jailed on many occasions along with thousands of his supporters. Peaceful Indian protests caused a public outcry and forced the South African General J. C. Smuts to negotiate a compromise with Gandhi. However, Gandhi supported the British in World War I and encouraged Indians to join the Army to defend the British Empire, in compliance with the full citizenship requirement.

Back in India, Gandhi became active in the struggle for Indian Independence. He spoke at the conventions of the Indian National Congress, becoming one of its leaders. In 1918, Gandhi opposed the increasing tax levied by the British during the devastating famine. He was arrested in Champaran, state Bihar, for organizing civil resistance of tens of thousands of landless farmers and serfs. In jail Gandhi was on a hunger strike in solidarity with the famine stricken farmers. Hundreds of thousands of his supporters gathered around the jail. Gandhi was addressed by the people as Mahatma (Great Soul) and Bapu (Father). He was released. Then he represented the farmers in negotiation with the British administration. His effort worked. The tax collection was suspended and all prisoners were released. He declared that all violence was evil after the Amritsar massacre of 379 civilians by British troops, which traumatized the Indian nation. As the leader of the Indian National Congress party Gandhi launched "Swaraj", a campaign for independence and non-cooperation with the British authorities. He urged Indians to replace British goods with their own fabrics and goods. He was imprisoned from 1922-1924, being released after an appendectomy. During that time a Swaraj party was formed by his anxious opponents; it later dissolved back into the Congress.

On New Year''s Eve, December 31, 1929, the Indian National Congress unfurled it''s flag of independence. Gandhi and Jawaharlal Nehru issued the Declaration of Independence on January 26, 1930. Gandhi planned to achieve stability through the secularization of India, as the only way of uniting Hindus and Muslims in one peaceful nation. The religious divide was growing under the British colonial rule, which prospered from the monopoly on the salt trade. Everyone needed salt. Gandhi wrote to the Viceroy, Lord Irwin: "If my letter makes no appeal to your heart, on the eleventh day of March I shall proceed with co-workers of the Ashram as I can take, to disregard the provisions of the Salt Laws. I regard this tax to be the most iniquitous of all from the poor man''s standpoint. As the Independence movement is essentially for the poorest in the land, the beginning will be made with this evil."

From March 12 to April 6, 1930, G', 'https://m.media-amazon.com/images/M/MV5BMjA1NTI5OTE4MF5BMl5BanBnXkFtZTcwNzUyNDEzOA@@._V1_QL75_UY207_CR6,0,140,207_.jpg', '1869-10-02', NULL, NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Ajeet Bharti', 'Indian independent journalist, author and media creator. He has worked with Times of India, Economic Times and IANS, later became founding editor of OpIndia Hindi, co-founded DO Politics, and heads AB4K Media. His books include Bakar Puran, Ghar Wapasi, There Will Be No Love, and Jo Bhi Kahunga Sach Kahunga.', 'https://www.hindustantimes.com/ht-img/img/2025/10/08/440x440/ajeet_bharti_1759869848810_1759869859528_1759897695382.jpg', '1994-09-24', 'Ratan Babhangaon, Begusarai, Bihar, India', NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Kushal Mehra', 'Indian podcaster, author and former textile entrepreneur based in Mumbai. He hosts the Cārvāka Podcast and describes his work as articulating Indian scepticism using Indian epistemological frameworks. He holds a master''s degree in philosophy and has written books including Nastik: Why I Am Not An Atheist and Blasphemy: Let Me Speak.', NULL, NULL, NULL, NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('J. Sai Deepak', 'Indian lawyer, author, columnist and public speaker. He is an engineer-turned-litigator practising primarily before the Supreme Court of India and the High Court of Delhi. He is the author of India That Is Bharat and India, Bharat and Pakistan.', NULL, '1985-11-23', 'Hyderabad, Telangana, India', NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Vikram Sampath', 'Indian historian, biographer and columnist known for biographies and works on Indian history and culture, including books on Gauhar Jaan, Savarkar and the Wadiyar dynasty of Mysore. He is a Fellow of the Royal Historical Society and founder of the Bangalore Literature Festival.', NULL, NULL, 'Bengaluru, Karnataka, India', NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Anand Ranganathan', 'Indian molecular biologist, professor, columnist and author. He is a professor at Jawaharlal Nehru University''s Special Centre for Molecular Medicine. His books include The Land of the Wilted Rose, For Love and Honour, The Rat Eater, Soufflé, and Hindus in Hindu Rashtra.', NULL, '1972-12-04', 'Tamil Nadu, India', NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Arun Shourie', 'Indian economist, investigative journalist, editor, author and former Union minister. He worked with the World Bank, edited The Indian Express and The Times of India, and served in the Vajpayee government. He is the author of numerous books on politics, religion, society and public affairs.', 'https://litfest.sgp1.cdn.digitaloceanspaces.com/uploads/authors/a-Zc5ss3CLGPWrn7LakKq7HRs9K7iHR7-metaMjguanBn-.jpg', '1941-11-02', 'Jalandhar, Punjab, India', NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Rajiv Malhotra', 'Indian-born American author, researcher and public intellectual focused on civilizations, Indian knowledge systems, religions and cross-cultural encounters. He founded Infinity Foundation and has authored books including Breaking India, Being Different, Indra''s Net and The Battle for Sanskrit.', NULL, '1950-09-15', 'New Delhi, Delhi, India', NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Meenakshi Jain', 'Indian historian and political scientist, formerly an associate professor of history at Gargi College, University of Delhi. Her research covers cultural and religious developments in medieval and early modern India. Her books include The Battle for Rama, Rama and Ayodhya, Sati, Flight of Deities and Rebirth of Temples, and Vishwanath Rises and Rises.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Meenakshi%20Jain.jpg', NULL, 'Delhi, India', NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('S. Gurumurthy', 'Swaminathan Gurumurthy is an Indian chartered accountant, columnist, economist and public intellectual. He is known for writing and speaking on economics, public policy, Indian civilization and political affairs, and has served in prominent public and institutional roles.', 'https://www.newsclick.in/sites/default/files/styles/amp_1200x675_16_9/public/2020-01/S%20Gurumurthy.jpeg?itok=g8xGjkSg', '1949-02-06', NULL, NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Swapan Dasgupta', 'Indian journalist, writer, political analyst and politician. He has written extensively on Indian politics, culture and Hindu nationalism and has served as a nominated member of the Rajya Sabha and in other public roles.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Swapan%20Dasgupta%20in%20May%202016.jpg', '1955-10-03', 'Kolkata, West Bengal, India', NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Ram Madhav', 'Indian politician, social leader, strategic thinker and author. He served as National General Secretary of the Bharatiya Janata Party from 2014 to 2020 and is associated with the India Foundation. His books include The New World, The Indian Reality, Partitioned Freedom and The Hindutva Paradigm.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ram%20Madhav%20at%20CPAC%20Hungary%202025.jpg', '1964-08-22', 'Amalapuram, Andhra Pradesh, India', NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Sanjeev Sanyal', 'Indian economist, writer and economic-policy adviser. He has served as Principal Economic Adviser in the Ministry of Finance and as a member of the Economic Advisory Council to the Prime Minister. He is also known for books on Indian history, geography and economic development.', NULL, '1970-08-27', 'Kolkata, West Bengal, India', NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Harsh Madhusudan', 'India-based public-markets investor and writer who has written on economics, finance and politics for publications including Mint, Swarajya, The Wall Street Journal, The Hindu Business Line and The Indian Express. He co-authored A New Idea of India with Rajeev Mantri.', NULL, NULL, NULL, NOW(6), NOW(6), 0, 'ADMIN');
INSERT INTO authors (name, biography, profile_image, date_of_birth, place_of_birth, created_at, updated_at, version, author_type) VALUES ('Koenraad Elst', 'Belgian author and orientalist whose work focuses heavily on Hinduism, Indian history, politics, comparative religion and the Hindutva movement. He has written extensively on the Ayodhya dispute and the Out-of-India theory and has worked as an independent researcher and writer.', 'https://commons.wikimedia.org/wiki/Special:FilePath/Koenraad%20Elst%20at%20Varanasi.jpg', '1959-08-07', 'Leuven, Belgium', NOW(6), NOW(6), 0, 'ADMIN');